### ISSUE TITLE
[v2] Unable to Build

### ISSUE THREAD

**Issue by lailton** [framework7io/Framework7#1891]
I am trying to build the last update and it is not working more.

**MacBook:Framework7 root# npm install
npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2017-10-17T02_20_27_086Z-debug.log
MacBook:Framework7 root#**

**MacBook:Framework7 root# npm run build-dev

> framework7@2.0.0-beta.11 build-dev /Developer/mobile/dev/Framework7
> cross-env NODE_ENV=development gulp build

module.js:529
    throw err;
    ^

Error: Cannot find module 'rollup-plugin-commonjs'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Developer/mobile/dev/Framework7/scripts/build-js.js:20:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! framework7@2.0.0-beta.11 build-dev: `cross-env NODE_ENV=development gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the framework7@2.0.0-beta.11 build-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2017-10-17T02_21_40_887Z-debug.log**

**Comment by J05HI** [comment]
@lailton
Looks like you need to execute npm install
A module is missing

**Comment by nolimits4web** [comment]
Yes, run `npm install` before doing build

**Comment by lailton** [comment]
I remove the folder node_modules and run again npm install and now it works.

Thanks guys
