### ISSUE TITLE
Error to build

### ISSUE THREAD

**Issue by lailton** [framework7io/framework7#2048]
I can not to compile the project.

![screen shot 2018-01-04 at 10 40 53 pm](https://user-images.githubusercontent.com/33045004/34590840-82cf2ee0-f1a0-11e7-835d-c1fe2cf82c94.png)
![screen shot 2018-01-04 at 10 41 07 pm](https://user-images.githubusercontent.com/33045004/34590842-83289b88-f1a0-11e7-8ffd-479e2fd877a7.png)

I have removed the node_modules. re-installed the NPM without success.

Any idea?

**Comment by nolimits4web** [comment]
Why do you build it? You probably don't need to do it. Try also update your Node and NPM

**Comment by lailton** [comment]
I did it and it doest not to work.

I did as is on the READ ME to build to use the command:

npm run build:dev

and it not to work.

**Comment by nolimits4web** [comment]
This readme is for F7 itself development, check http://framework7.io/docs/installation.html

**Comment by lailton** [comment]
Hi,

Sorry but it no make sense, What I am doing is trying to build by my own using the GIT repository to have the final files ( prod / dev ).

I am doing the:
git clone https://github.com/framework7io/framework7.git
cd framework7
npm install --global gulp
npm install

Until here everything is ok, but If I call this command:

```
sh-3.2# npm run build:prod

> framework7@2.0.5 build:prod /Developer/system/git/framework7
> cross-env NODE_ENV=production gulp build

[15:29:29] Using gulpfile /Developer/system/git/framework7/gulpfile.js
(node:3371) ExperimentalWarning: The http2 module is an experimental API.
[15:29:29] Starting 'js'...
[15:29:29] Starting 'less'...
[15:29:29] Starting 'components'...
[15:29:47] Finished 'less' after 19 s
[15:29:51] Finished 'components' after 22 s
/Developer/system/git/framework7/node_modules/cloneable-readable/index.js:38
    throw new Error('already started')
    ^

Error: already started
    at Cloneable.clone (/Developer/system/git/framework7/node_modules/cloneable-readable/index.js:38:11)
    at File.clone (/Developer/system/git/framework7/node_modules/vinyl-source-stream/node_modules/vinyl/index.js:117:30)
    at BufferList._callback (/Developer/system/git/framework7/node_modules/vinyl-buffer/index.js:18:19)
    at BufferList.end (/Developer/system/git/framework7/node_modules/vinyl-buffer/node_modules/bl/bl.js:83:10)
    at Cloneable.onend (/Developer/system/git/framework7/node_modules/cloneable-readable/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:254:19)
    at Cloneable.emit (events.js:164:20)
    at endReadableNT (/Developer/system/git/framework7/node_modules/cloneable-readable/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! framework7@2.0.5 build:prod: `cross-env NODE_ENV=production gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the framework7@2.0.5 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-08T17_29_54_086Z-debug.log
sh-3.2#
```

The log file is: /var/root/.npm/_logs/2018-01-08T17_29_54_086Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.3.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:prod' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle framework7@2.0.5~prebuild:prod: framework7@2.0.5
6 info lifecycle framework7@2.0.5~build:prod: framework7@2.0.5
7 verbose lifecycle framework7@2.0.5~build:prod: unsafe-perm in lifecycle true
8 verbose lifecycle framework7@2.0.5~build:prod: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Developer/system/git/framework7/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle framework7@2.0.5~build:prod: CWD: /Developer/system/git/framework7
10 silly lifecycle framework7@2.0.5~build:prod: Args: [ '-c', 'cross-env NODE_ENV=production gulp build' ]
11 silly lifecycle framework7@2.0.5~build:prod: Returned: code: 1  signal: null
12 info lifecycle framework7@2.0.5~build:prod: Failed to exec build:prod script
13 verbose stack Error: framework7@2.0.5 build:prod: cross-env NODE_ENV=production gulp build
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid framework7@2.0.5
15 verbose cwd /Developer/system/git/framework7
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/Cellar/node/9.3.0_1/bin/node" "/usr/local/bin/npm" "run" "build:prod"
18 verbose node v9.3.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error framework7@2.0.5 build:prod: cross-env NODE_ENV=production gulp build
22 error Exit status 1
23 error Failed at the framework7@2.0.5 build:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**So, my question is, How to solve it?

Note, I know that I can to download and use the last version css / js compiled, but I really would like to be able to compile by myself.

Can you to help?**

**Comment by lailton** [comment]
@nolimits4web ?

**Comment by nolimits4web** [comment]
To be honest don't know what is happening, i'm on Node v8.9.3 and NPM v5.5.1 and everything works fine for me
