### ISSUE TITLE
Simply following install instructions, running i.e. npm run core:dev fails

### ISSUE THREAD

**Issue by abletaz** [framework7io/framework7#2886]
After cloning the git repo and npm installing gulp, when I run npm run core:prod / core:dev, the following error is output (on MacOS):

npm run core:prod

> framework7-source@0.0.0 core:prod /Users/michaelbevin/dev/framework7
> cross-env-shell NODE_ENV=production "gulp ks-core && gulp server-core"

..../framework7/scripts/gulpfile.js:81
    ));
    ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (..../framework7/gulpfile.js:1:63)

**Comment by nolimits4web** [comment]
Make sure you are using recent node and npm
