### ISSUE TITLE
Cant build from master

### ISSUE THREAD

**Issue by Meettya** [framework7io/framework7#2897]
Cant build `build-react:prod` from master commit 0ba6ae2
Wiil try `npm run-script build-react:prod` and `gulp phenome`

Both get error:

```
/Users/meettya/git_hub/framework7/scripts/gulpfile.js:81
    ));
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/meettya/git_hub/framework7/gulpfile.js:1:63)
```

Checked at 2 system:
1) MacOS X 10.12.6 (16G29) & node v6.14.4 & npm 3.10.10
2) Linux Xubuntu 18.04 & node v6.14.4 & npm 3.10.10 (Virtualbox)

May be I use wrong node version? Please add system requirements information for build process to Readme.

**Comment by nolimits4web** [comment]
Update node to 9+ and npm. Otherwise, use one of available templates
