### ISSUE TITLE
react:dev and vue:dev npm scripts fails with a SyntaxError

### ISSUE THREAD

**Issue by blikblum** [framework7io/framework7#2987]
* Framework7 version: [e.g. 4.0.0]
* React.js version: [e.g. 16.0.0]
* Platform and Target: [Chrome browser]

### Describe the bug
Trying to run react:dev or vue:dev  fails with the following error

```
{ SyntaxError: Unexpected token (7:4)
    at Parser.pp$4.raise (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:2684:13)
    at Parser.pp.unexpected (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:641:8)
    at Parser.pp$3.parseIdent (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:2639:10)
    at Parser.pp$3.parsePropertyName (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:2423:105)
    at Parser.pp$3.parseProperty (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:2354:8)
    at Parser.pp$3.parseObj (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:2334:23)
    at Parser.pp$3.parseExprAtom (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:2134:17)
    at Parser.parseExprAtom (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\inject.js:399:24)
    at Parser.pp$3.parseExprSubscripts (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:2002:19)
    at Parser.pp$3.parseMaybeUnary (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:1979:17)
    at Parser.pp$3.parseExprOps (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:1921:19)
    at Parser.pp$3.parseMaybeConditional (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:1904:19)
    at Parser.pp$3.parseMaybeAssign (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:1880:19)
    at Parser.pp$3.parsePropertyValue (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:2370:87)
    at Parser.pp$3.parseProperty (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:2361:8)
    at Parser.pp$3.parseObj (D:\repositories\Framework7\node_modules\phenome\node_modules\acorn-jsx\node_modules\acorn\dist\acorn.js:2334:23) pos: 139, loc: Position { line: 7, column: 4 }, raisedAt: 142 }

```
### To Reproduce
1. clone a clean copy of master branch
2. npm install
3. npm run react:dev

### Expected behavior
Should build

### Actual Behavior
Crashes and aborts build

### Additional context
Using Windows 10, Node v8

**Comment by nolimits4web** [comment]
Updated dependencies and works fine for me now

**Comment by blikblum** [comment]
After the update worked. Thanks
