### ISSUE TITLE
Could not use framework7 create --ui to create a project in macOS

### ISSUE THREAD

**Issue by Sicmatr1x** [framework7io/framework7#3056]
When I use node.js v10.15.3(macOS 10.13.6) to create the freamework7 project by use framework7-cli tool I found it always throw this error.
I try many method to solve this problem include rebuild and uninstall node

```
sicmatr1xMacBook-Pro:f7demo sicmatr1x$ sudo framework7 create --ui
/usr/local/lib/node_modules/framework7-cli/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/build/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/build/Debug/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/build/Release/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/out/Debug/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/Debug/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/out/Release/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/Release/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/build/default/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/compiled/10.15.3/darwin/x64/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/addon-build/release/install-root/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/addon-build/debug/install-root/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/addon-build/default/install-root/sharp.node
 → /usr/local/lib/node_modules/framework7-cli/node_modules/sharp/lib/binding/node-v64-darwin-x64/sharp.node
    at bindings (/usr/local/lib/node_modules/framework7-cli/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/framework7-cli/node_modules/sharp/lib/constructor.js:10:34)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/framework7-cli/node_modules/sharp/lib/index.js:3:15)
```

**Comment by nolimits4web** [comment]
You can see a lot of advices on forum https://forum.framework7.io/t/i-am-getting-error-while-installing-the-framework7-cli/5950 or here https://forum.framework7.io/t/new-framework7-cli-feedback-needed/5373/32

**Comment by ezani92** [comment]
Hi. im facing this same issues. any solution? i try all the advices but cant make it work
