### ISSUE TITLE
Can't install Kitchen Sink

### ISSUE THREAD

**Issue by Twilight0** [framework7io/framework7#3097]
### Versions
* Framework7 version: 4.2.0
* Platform and Target: Ubuntu Linux 18.04.2 (kernel: 4.15.0-46-generic)

### Describe the bug
I am not able to install framework7's Kitchen Sink. Gulp was installed via distribution's package manager.

### To Reproduce
I am running

> npm run core:prod

```
npm ERR! missing script: core:prod
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/twilight/Worker/GitHub/nodejs/framework7/npm-debug.log
```

### Expected behavior
Successfully install of Kitchen Sink.

### Actual Behavior
**This:**
```
npm ERR! Linux 4.15.0-46-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "core:prod"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2

npm ERR! missing script: core:prod
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/twilight/Worker/GitHub/nodejs/framework7/npm-debug.log
```

### Additional context
**Debug log:**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'core:prod' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose stack Error: missing script: core:prod
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/share/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:232:12
4 verbose stack     at /usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd /media/twilight/Worker/GitHub/nodejs/framework7
6 error Linux 4.15.0-46-generic
7 error argv "/usr/bin/node" "/usr/bin/npm" "run" "core:prod"
8 error node v8.10.0
9 error npm  v3.5.2
10 error missing script: core:prod
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by Twilight0** [comment]
I am closing this issue, found help in the forums:
http://forum.framework7.io/t/solved-cant-install-kitchen-sink/6397
