### ISSUE TITLE
ReferenceError: window is not defined when using NextJs

### ISSUE THREAD

**Issue by dieguit** [framework7io/framework7#3442]
* Framework7 version: framework7@5.2.0
* React.js version: react@16.12.0
* Platform and Target: Chrome browser

### Describe the bug
When using Next-JS, importing `framework7-react` causes this error (Call stack in the bottom). 
This issue is somehow related: https://github.com/framework7io/framework7/issues/2498

### To Reproduce
1. Install next-js and create a simple app
2. Install f7 and f7-react
3. In the main page, `import Framework7React from 'framework7-react';`
4. Error makes the app crash

### Expected behavior
Server-side rendering should be supported with `ssr-window`

### Actual Behavior
App crashing

Trace:
```
ReferenceError: window is not defined
    at [...]/app/.next/server/static/development/pages/_app.js:4109:34
    at module.exports../node_modules/framework7-react/framework7-react.bundle.js (/Users/dieguit/projects/victu/victu-app/.next/server/static/development/page
s/_app.js:2714:28)
    at Object../node_modules/framework7-react/framework7-react.bundle.js (/Users/dieguit/projects/victu/victu-app/.next/server/static/development/pages/_app.j
s:2715:3)
    at __webpack_require__ (/Users/dieguit/projects/victu/victu-app/.next/server/static/development/pages/_app.js:23:31)
    at Module../pages/_app.js (/Users/dieguit/projects/victu/victu-app/.next/server/static/development/pages/_app.js:66083:74)
    at __webpack_require__ (/Users/dieguit/projects/victu/victu-app/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/dieguit/projects/victu/victu-app/.next/server/static/development/pages/_app.js:66115:18)
    at __webpack_require__ (/Users/dieguit/projects/victu/victu-app/.next/server/static/development/pages/_app.js:23:31)
    at /Users/dieguit/projects/victu/victu-app/.next/server/static/development/pages/_app.js:91:18
    at Object.<anonymous> (/Users/dieguit/projects/victu/victu-app/.next/server/static/development/pages/_app.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
```

**Comment by nolimits4web** [comment]
Would be great maybe to see some simple/demo repo where it can be reproduced

**Comment by dieguit** [comment]
Sorry for the late response, here is a repo: https://github.com/dieguit/tmp-framwork7-nextjs
Just `yarn && yarn dev` to start the dev environment.

**Comment by cruzlutor** [comment]
Do you have any news about this? I'm interested in to use framework7 components on small Nextjs project, Is it ready for SSR?

**Comment by AlexSmirnov9107** [comment]
any updates?

**Comment by hongnk** [comment]
I made it to work here:
[_app.js.txt](https://github.com/framework7io/framework7/files/4614917/_app.js.txt)

note: still small error cannot redefined $f7, but it willr eload and work, perhaps can solve by movng f7 initialize code to index.js

**Comment by AlexSmirnov9107** [comment]
![image](https://user-images.githubusercontent.com/32673518/81796178-e4ed1b80-952e-11ea-8bd9-2d895cecdcbb.png)

**Comment by hongnk** [comment]
@AlexSmirnov9107 you can follow the sample code I posted earlier (do not import 'framework7-react')
