### ISSUE TITLE
ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.

### ISSUE THREAD

**Issue by bryceandy** [framework7io/framework7#3745]
* Framework7 version: 5.7.13
* Platform and Target: Cordova Android ^9.0.0, Cordova iOS ^6.1.1

### Describe the bug
There appears to be a problem with the terser-webpack-plugin (currently version ^5.0.0) and webpack(^4.44.2). From a fresh install, when you run `npm run build-dev-cordova` webpack throws the error:

```
/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:104
    throw new _ValidationError.default(errors, schema, configuration);
    ^

ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, parallel?, minify?, terserOptions?, extractComments? }
    at validate (/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at new TerserPlugin (/node_modules/terser-webpack-plugin/dist/index.js:32:31)
    at Object.<anonymous> (/build/webpack.config.js:55:17)
{
  name: 'ValidationError',
  errors: [
    {
      keyword: 'additionalProperties',
      dataPath: '',
      schemaPath: '#/additionalProperties',
      params: [Object],
      message: 'should NOT have additional properties',
      schema: false,
      parentSchema: [Object],
      data: [Object]
    }
  ],
  schema: {
    definitions: { Rule: [Object], Rules: [Object] },
    title: 'TerserPluginOptions',
    type: 'object',
    additionalProperties: false,
    properties: {
      test: [Object],
      include: [Object],
      exclude: [Object],
      parallel: [Object],
      minify: [Object],
      terserOptions: [Object],
      extractComments: [Object]
    }
  },
  headerName: 'Terser Plugin',
  baseDataPath: 'options',
  postFormatter: null,
  message: 'Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.\n' +
    " - options has an unknown property 'sourceMap'. These properties are valid:\n" +
    '   object { test?, include?, exclude?, parallel?, minify?, terserOptions?, extractComments? }'
}
```

### To Reproduce
1. Create a new framework7 project `framework7 create`, use webpack as the preferred bundler
2. Run `npm run build-dev-cordova`
3. See error

### Expected behavior
A new project should build as in the previous versions

### Actual Behavior
The terser webpack plugin throws the error

### Additional context
Previous versions of f7(5.7.12), webpack(4.44.2) and the terser plugin(4.2.2) did not throw this error.

**Comment by EloFran** [comment]
hi @bryceandy ,
[its just open here](https://github.com/framework7io/framework7/issues/3743)
