### ISSUE TITLE
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js)

### ISSUE THREAD

**Issue by tmwebs** [framework7io/framework7#3926]
* Framework7 version:  4.1.0
* Platform and Target: Cordova 10.0.0 

### Describe the bug
I have the following problem when using “npm run build-cordova”:

ERROR in ./src/css/icons.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: url.replace is not a function
    at new RelativeURL (/Users/toni/Desarrollo/APP/jp/node_modules/css-loader/dist/cjs.js!/Users/toni/Desarrollo/APP/jp/node_modules/postcss-loader/dist/cjs.js!/Users/toni/Desarrollo/APP/jp/src/css/icons.css:335:35)
    at Object.627 (/Users/toni/Desarrollo/APP/jp/node_modules/css-loader/dist/cjs.js!/Users/toni/Desarrollo/APP/jp/node_modules/postcss-loader/dist/cjs.js!/Users/toni/Desarrollo/APP/jp/src/css/icons.css:19:56)
    at __webpack_require__ (/Users/toni/Desarrollo/APP/jp/node_modules/css-loader/dist/cjs.js!/Users/toni/Desarrollo/APP/jp/node_modules/postcss-loader/dist/cjs.js!/Users/toni/Desarrollo/APP/jp/src/css/icons.css:281:41)
    at /Users/toni/Desarrollo/APP/jp/node_modules/css-loader/dist/cjs.js!/Users/toni/Desarrollo/APP/jp/node_modules/postcss-loader/dist/cjs.js!/Users/toni/Desarrollo/APP/jp/src/css/icons.css:353:37
    at Object.<anonymous> (/Users/toni/Desarrollo/APP/jp/node_modules/css-loader/dist/cjs.js!/Users/toni/Desarrollo/APP/jp/node_modules/postcss-loader/dist/cjs.js!/Users/toni/Desarrollo/APP/jp/src/css/icons.css:356:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at evalModuleCode (/Users/toni/Desarrollo/APP/jp/node_modules/mini-css-extract-plugin/dist/utils.js:46:10)
    at /Users/toni/Desarrollo/APP/jp/node_modules/mini-css-extract-plugin/dist/loader.js:299:51
    at /Users/toni/Desarrollo/APP/jp/node_modules/webpack/lib/Compiler.js:548:11
    at /Users/toni/Desarrollo/APP/jp/node_modules/webpack/lib/Compiler.js:1118:17
 @ ./src/js/app.js 6:0-26

webpack 5.46.0 compiled with 1 error in 13292 ms

Build failed with errors.

**Comment by nolimits4web** [comment]
Duplicate https://github.com/framework7io/framework7/issues/3924
