### ISSUE TITLE
rimraf error when: npm run build-cordova

### ISSUE THREAD

**Issue by kylex** [framework7io/framework7#4137]
- Framework7 version: 7.1.5
- Platform and Target: Cordova (Android and iOS)
- MacOS Ventura 13.2.1
- npm 9.5.0 

A thorough description of the bug can be found on the forum, along with a potential fix:
https://forum.framework7.io/t/error-rimraf-when-npm-run-build-cordova/16112/7

Basic error is, when running 
npm run build-cordova
or
npm run build-cordova-ios
or 
npm run build-cordova-android

The following error occurs:
```
Users/myinfo/Sites/my-app/node_modules/rimraf/dist/cjs/src/index.js:21
        throw new Error('invalid rimraf options');
              ^

Error: invalid rimraf options
    at assertRimrafOptions (Users/myinfo/Sites/my-app/node_modules/rimraf/dist/cjs/src/index.js:21:15)
    at exports.default (Users/myinfo/Sites/my-app/node_modules/rimraf/dist/cjs/src/opt-arg.js:5:40)
    at Users/myinfo/Sites/my-app/node_modules/rimraf/dist/cjs/src/index.js:32:46
    at Object.<anonymous> (Users/myinfo/Sites/my-app/build/build.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by 15696045354** [comment]
"rimraf": "^3.0.2",

**Comment by nolimits4web** [comment]
This issue was incorrectly closed on 2026-05-19 by a compromised credential (Shai-Hulud npm supply-chain worm). Reopening — apologies for the noise.
