### ISSUE TITLE
browserHistory throwing error when used with StrictMode

### ISSUE THREAD

**Issue by BastianW13** [framework7io/framework7#4278]
- Framework7 version: 8.3.3 
- React.js version: ^18.0.0
- Platform and Target: Desktop/Web (tested with Brave, Firefox and Edge Browser)
- Live Link or CodeSandbox: https://codesandbox.io/p/sandbox/browserhistory-issue-mwe-lt7w3w

### Describe the bug

Trying to use View parameter `browserHistory` in combination with `React.StrictMode` runs into an error when navigating back to the previous page. 

<details>
<summary>Error Message</summary>

Cannot read properties of undefined (reading 'children')
TypeError: Cannot read properties of undefined (reading 'children')
    at getChildrenArray (http://localhost:3002/slug/static/js/bundle.js:73974:26)
    at Router.pageComponentLoader (http://localhost:3002/slug/static/js/bundle.js:74020:30)
    at load (http://localhost:3002/slug/static/js/bundle.js:106505:14)
    at http://localhost:3002/slug/static/js/bundle.js:106626:9
    at Array.forEach (<anonymous>)
    at resolve (http://localhost:3002/slug/static/js/bundle.js:106623:65)
    at http://localhost:3002/slug/static/js/bundle.js:106719:7
    at enterNextRoute (http://localhost:3002/slug/static/js/bundle.js:106791:7)
    at leaveCurrentRoute (http://localhost:3002/slug/static/js/bundle.js:106804:7)
    at Router.processRouteQueue (http://localhost:3002/slug/static/js/bundle.js:106807:3)

</details>

### To Reproduce

Steps to reproduce the behavior (see codesandbox above):

1. Navigate to either 'About' or 'Credits'
2. Click on back arrow in `NavBar` component
2.1 Alternative: Use browser navigation to go back

### Expected behavior

Navigation back to the previous page without throwing errors.

### Actual Behavior

Navigation to the previous page but with errors.

### Additional Context

In my actual application the navigation to the previous page still works (error messages can just be closed), but without actually updating the classes of `previous-page` and `current-page`. This leads to a frozen state, where nothing can be selected. Manually changing the `previous-page` class to `current-page` "unfreezes" the page.   
However, i can not replicate that behaviour and it might not be solely related to framework7.

**Comment by 1619626107** [comment]
1619626107
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "framework7io/framework7"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月5日(星期五) 晚上6:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[framework7io/framework7] browserHistory throwing error when used with StrictMode (Issue #4278)





  
Framework7 version: 8.3.3
 
React.js version: ^18.0.0
 
Platform and Target: Desktop/Web (tested with Brave, Firefox and Edge Browser)
 
Live Link or CodeSandbox: https://codesandbox.io/p/sandbox/browserhistory-issue-mwe-lt7w3w
  
Describe the bug
 
Trying to use View parameter browserHistory in combination with React.StrictMode runs into an error when navigating back to the previous page.
  Error Message 
Cannot read properties of undefined (reading 'children')
 TypeError: Cannot read properties of undefined (reading 'children')
 at getChildrenArray (http://localhost:3002/slug/static/js/bundle.js:73974:26)
 at Router.pageComponentLoader (http://localhost:3002/slug/static/js/bundle.js:74020:30)
 at load (http://localhost:3002/slug/static/js/bundle.js:106505:14)
 at http://localhost:3002/slug/static/js/bundle.js:106626:9
 at Array.forEach ()
 at resolve (http://localhost:3002/slug/static/js/bundle.js:106623:65)
 at http://localhost:3002/slug/static/js/bundle.js:106719:7
 at enterNextRoute (http://localhost:3002/slug/static/js/bundle.js:106791:7)
 at leaveCurrentRoute (http://localhost:3002/slug/static/js/bundle.js:106804:7)
 at Router.processRouteQueue (http://localhost:3002/slug/static/js/bundle.js:106807:3)
  
To Reproduce
 
Steps to reproduce the behavior (see codesandbox above):
  
Navigate to either 'About' or 'Credits'
 
Click on back arrow in NavBar component
 2.1 Alternative: Use browser navigation to go back
 
See error
  
Expected behavior
 
Navigation back to the previous page without throwing errors.
 
Actual Behavior
 
Navigation to the previous page but with errors.
 
Additional Context
 
In my actual application the navigation to the previous page still works (error messages can just be closed), but without actually updating the classes of previous-page and current-page. This leads to a frozen state, where nothing can be selected. Manually changing the previous-page class to current-page "unfreezes" the page.
 However, i can not replicate that behaviour and it might not be solely related to framework7.

**Comment by 1619626107** [comment]
飞艇 百家乐 棋牌 跟我干半小时 300 挣 500 q：2789996884 






































































































































只要心情是晴朗的，人生就没有雨天。无论何时，都要记得给自己一个微笑，无论你过去做了什么，将来即将做什么，生活中依旧有许多值得感恩的。




心有期待，以感恩的心感谢一路陪伴的所有，艰辛坎坷的路上，给自己一个微笑，是对自己的一个肯定，也是对未来的一份期许。任何的收获都不是巧合，而是每天努力与坚持的结果。






&nbsp;

**Comment by nolimits4web** [comment]
This issue was incorrectly closed on 2026-05-19 by a compromised credential (Shai-Hulud npm supply-chain worm). Reopening — apologies for the noise.
